name: CustomPlayerNametags
version: '1.0.1'
main: afx.customplayernametags.CustomPlayerNametags
api-version: '1.20'
author: AFXPlugins
description: >
  Fully customizable player nametags.

depend: [packetevents]
softdepend: [PlaceholderAPI]

commands:
  nametags:
    description: CustomPlayerNametags commands
    usage: /nametags reload | /nametags update | /nametags format view | /nametags format set | /nametags format reset
    aliases: [customplayernametags]
    permission: customplayernametags.admin
    permission-message: You do not have permission to use this command.

permissions:
  customplayernametags.admin:
    description: Allows use of all CustomPlayerNametags commands.
    default: op
  customplayernametags.updatenotify:
    description: Receive a message on join when a new plugin update is available.
    default: op
