package afx.customplayernametags.manager;

import afx.customplayernametags.CustomPlayerNametags;
import afx.customplayernametags.config.*;
import afx.customplayernametags.format.NametagFormatPermissions;
import afx.customplayernametags.format.TemplateMarkers;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.block.BlockState;
import org.bukkit.block.Sign;
import org.bukkit.block.sign.Side;
import org.bukkit.entity.Player;
import org.bukkit.event.block.SignChangeEvent;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.*;

/**
 * Persistent chunk editor. A format is never represented by one opaque item:
 * text, placeholders, colour/style tags and newlines are independently editable.
 *
 * <p>Every menu's fixed action buttons (slot, item, display name, and
 * hover-tooltip lore) are read from {@link GuiConfigManager} — see
 * {@code gui.yml} — with the literals passed to each
 * {@link GuiConfigManager#button} call here serving only as the fallback
 * used when a value is missing from both the on-disk file and the bundled
 * default.
 */
public final class NametagEditorManager {
    private enum View { EDITOR, ADD_ITEM, PLACEHOLDERS, COLORS, DETAIL, ADMIN, PLAYERS, GROUPS, MAIN, CONFIRM_DELETE_CHUNK,
        WIDGET_TOGGLES, WIDGET_CONTENTS, WIDGET_ITEM_DETAIL, WIDGET_ADD_ITEM, WIDGET_COLORS, WIDGET_PLACEHOLDERS,
        GLOBAL_PLATFORM_CHOICE, GROUPS_PLATFORM_CHOICE, CONFIRM_DELETE_WIDGET }
    /** PLAYER_EDIT is a player editing whatever admin-set nametag format currently applies to them (their own UUID carried in {@link Session#targetId}); it replaces the old player-authored preset system. */
    private enum Target { GLOBAL, PLAYER, GROUP, PLAYER_EDIT }
    /**
     * WIDGET is the one admin-template-only chunk kind — see
     * {@link TemplateMarkers} for the {@code {widget ...}...{/widget}} tag
     * text it serializes to in the raw format string that's actually
     * persisted.
     */
    private enum Kind { TEXT, PLACEHOLDER, COLOR, NEWLINE, WIDGET }
    /**
     * One piece of a format. {@code value} always holds the exact string
     * this chunk serializes back to (see {@link #serialize}) — for
     * TEXT/PLACEHOLDER/COLOR/NEWLINE that's just the literal text/tag; for
     * WIDGET it's the corresponding {@link TemplateMarkers} widget tag.
     * {@code widgetContents} and the four {@code widget*} fields only mean
     * anything for a {@code WIDGET} chunk — see {@link #resyncWidget}, which
     * is what keeps a widget's {@code value} in sync with its contents
     * after any edit.
     *
     * <p>Deliberately a plain (non-record) nested class: unlike the other
     * three kinds, a Widget needs its own small nested chunk list plus
     * several flags, which a two-field record can't hold, and giving every
     * kind that same shape keeps {@link #chunkItem}/{@link #serialize}
     * uniform instead of splitting widgets into a parallel data structure.
     */
    private static final class Chunk {
        Kind kind; String value;
        List<Chunk> widgetContents; boolean widgetColors = true, widgetPlaceholders = true, widgetText = true;
        /** Maximum visible characters allowed in any one TEXT item typed into this widget, or {@code -1} for no limit — see {@link #sanitizeWidgetText}. Only meaningful on a {@code WIDGET} chunk. */
        int widgetCharacterLimit = -1;
        /**
         * This widget's stable id — see {@link TemplateMarkers.Widget#id()}.
         * Only meaningful on a {@code WIDGET} chunk. Minted once, up front,
         * for a brand-new widget (see the {@code widget-toggles-menu}
         * "add" handler) and carried straight through unchanged for a
         * widget parsed back out of an existing format's tag (see
         * {@link #parseToken}) — never regenerated by {@link #resyncWidget}
         * on subsequent edits, so a player's already-stored fill (keyed by
         * this same id) stays attached to it.
         */
        String widgetId = "";
        Chunk(Kind kind, String value) { this.kind = kind; this.value = value; }
    }
    private record Holder(UUID player, View view, int selected) implements InventoryHolder { public Inventory getInventory(){return null;} }
    /** One logical line (a run of chunks between newlines) of the chunk grid, in chunk-index order. */
    private record Row(List<Integer> indices) {}
    private static final int FORMAT_SLOTS = 45;
    /** Rows of chunk grid actually visible at once (45 slots / 9 columns). Formats with more logical lines than this scroll vertically via {@link Session#scrollRow}; a single line longer than 9 chunks scrolls horizontally via {@link Session#scrollCol}. */
    private static final int VISIBLE_ROWS = FORMAT_SLOTS / 9;
    private static final int ROW_WIDTH = 9;
    private static final Pattern TOKEN = Pattern.compile("(\\\\n|\\n|\\{player\\}|%[^%\\n]+%|&(?:#[0-9a-fA-F]{6}|[0-9a-fk-orA-FK-OR])|<[^>]+>|"
            + TemplateMarkers.MARKER.pattern() + ")");
    private static final Pattern INLINE_COLOR = Pattern.compile("&#[0-9A-Fa-f]{6}|&[0-9a-fk-orA-FK-OR]|<[^>]+>");
    private static final Pattern INLINE_PLACEHOLDER = Pattern.compile("%[^%\\n]+%");
    private final CustomPlayerNametags plugin; private final ConfigManager config; private final NametagManager manager;
    private final EditorPlaceholderStore placeholders; private final MessageManager messages;
    private final GuiConfigManager guiConfig;
    private final Map<UUID, Session> sessions = new ConcurrentHashMap<>();
    private static final class Session {
        final List<Chunk> chunks; final Target target; final String targetId; final Map<Integer,Integer> displayed = new HashMap<>();
        /** Index (in logical lines, not chunk indices) of the first line currently shown. Lets a format with more lines than fit vertically scroll. */
        int scrollRow;
        /** Column offset (in chunks) every visible line is windowed from. Lets a single line with more than 9 chunks scroll horizontally instead of wrapping into extra rows. */
        int scrollCol;
        /** True while the sign editor is open collecting a text chunk — see {@link #openSignInput} and {@link #handleSignChange}. */
        boolean awaitingSign;
        BlockState temporarySign;
        /** What the currently-open sign editor's submitted text means: {@code null} for a plain format-text chunk, {@code "widget-text"} for text being added inside a widget's slot, or {@code "widget-character-limit"} for the widget-toggles-menu's per-widget character limit entry — see {@link #handleSignChange}. */
        String signMode;
        /** Index into {@link #chunks} of the WIDGET chunk currently open on a WIDGET_* view — including the WIDGET_TOGGLES page when it's editing that widget's existing permissions rather than configuring a brand-new one — or {@code null} outside those views/while creating a new widget. See {@link #openWidgetToggles} and {@link #openWidgetPermissions}. */
        Integer widgetIndex;
        /** Pending allowed-item-type toggles and character limit for a brand-new (or being-re-permissioned) widget, shown on the WIDGET_TOGGLES page before they're actually applied — see {@link #openWidgetToggles}/{@link #openWidgetPermissions}. */
        boolean pendingWidgetColors = true, pendingWidgetPlaceholders = true, pendingWidgetText = true;
        int pendingWidgetCharacterLimit = -1;
        /** Whether this session is editing the Bedrock variant of a Global/Group format instead of the normal (Java) one — see {@link #openBedrockChoice}. Always false for PLAYER/PLAYER_EDIT, which have no separate Bedrock variant. */
        boolean bedrock;
        Session(String raw, Target target, String id) { this.chunks=parse(raw); this.target=target; this.targetId=id; }
    }
    public NametagEditorManager(CustomPlayerNametags plugin, ConfigManager config, NametagManager manager,
                                MessageManager messages, EditorPlaceholderStore placeholders,
                                GuiConfigManager guiConfig) {
        this.plugin=plugin; this.config=config; this.manager=manager; this.placeholders=placeholders;
        this.messages=messages; this.guiConfig=guiConfig;
    }
    /** Opens the top-level {@code /nametag} menu: View, Toggle, Edit Nametag. */
    public void openMainMenu(Player p) {
        sessions.remove(p.getUniqueId());
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.MAIN,-1),27,guiConfig.title("main-menu",ChatColor.DARK_BLUE+"Nametag Menu"));
        put(inv,guiConfig.button("main-menu","edit",11,Material.ANVIL,"&bEdit Nametag","&7Edit the nametag format currently applied to you"));
        put(inv,guiConfig.button("main-menu","view",13,Material.OAK_SIGN,"&fView","&7See your current nametag format"));
        boolean hidden=manager.hasNametagsHidden(p.getUniqueId());
        put(inv, hidden
                ?guiConfig.button("main-menu","toggle-hidden",15,Material.RED_DYE,"&cNametags Hidden","&7Click to see other players' nametags again")
                :guiConfig.button("main-menu","toggle-visible",15,Material.LIME_DYE,"&aNametags Visible","&7Click to stop seeing other players' nametags"));
        put(inv,guiConfig.button("main-menu","close",22,Material.BARRIER,"&cClose"));
        p.openInventory(inv);
    }
    /** Sends the player's current effective nametag format, parsed exactly as it renders in-game — the "View" main-menu button. */
    private void sendCurrentFormat(Player p) {
        String raw=manager.getEffectiveRawFormat(p);
        messages.send(p,"nametag-view-header");
        p.sendMessage(afx.customplayernametags.format.NametagFormatter.toComponent(manager.parseFormat(p,raw)));
    }
    public void cancel(UUID uuid) { Session s=sessions.remove(uuid); if(s!=null)restoreTemporarySign(s); }
    /** Opens Paper's native sign editor for text input; no anvil GUI/library is used. */
    private void openTextChunkSign(Player p, Session s) {
        s.signMode=null; openSignInput(p,s,new String[]{"Enter text","","",""});
    }
    /** Opens the sign editor to collect a whole number for a Characters item — see {@link #handleSignChange}. */
    private void openNumberSign(Player p, Session s, String mode) {
        s.signMode=mode; openSignInput(p,s,new String[]{"Enter a number","","",""});
    }
    /** Opens the sign editor to collect text for a widget's inner slot — see {@link #handleSignChange}. */
    private void openWidgetTextSign(Player p, Session s) {
        s.signMode="widget-text"; openSignInput(p,s,new String[]{"Enter text","","",""});
    }
    private void openSignInput(Player p, Session s, String[] lines) {
        Block block=findTemporarySignBlock(p);
        if(block==null){
            p.sendMessage(ChatColor.RED+"Unable to find room to open the sign editor.");
            openEditor(p);
            return;
        }
        s.awaitingSign=true; s.temporarySign=block.getState(); block.setType(Material.OAK_SIGN, false);
        Sign sign=(Sign)block.getState();
        for(int i=0;i<4;i++)sign.setLine(i,lines[i]);
        sign.update(true,false); p.openSign(sign, Side.FRONT);
    }
    private Block findTemporarySignBlock(Player p) {
        Location base=p.getLocation().getBlock().getLocation();
        for(int y=2;y<=8;y++) for(int x=-1;x<=1;x++) for(int z=-1;z<=1;z++) { Block b=base.clone().add(x,y,z).getBlock(); if(b.getType().isAir())return b; }
        return null;
    }
    public void handleSignChange(SignChangeEvent event) {
        Player p=event.getPlayer(); Session s=sessions.get(p.getUniqueId());
        if(s==null||!s.awaitingSign||s.temporarySign==null||!event.getBlock().getLocation().equals(s.temporarySign.getLocation()))return;
        event.setCancelled(true); restoreTemporarySign(s);
        StringBuilder text=new StringBuilder(); for(String line:event.getLines())if(line!=null)text.append(line);
        String entered=text.toString().trim(); String mode=s.signMode; s.signMode=null;
        if("widget-character-limit".equals(mode)){
            // Blank input (or anything that doesn't parse) means "no limit" — unlike the
            // widget-text flow there's no reason to bounce the player back to re-enter it,
            // since -1 (unlimited) is a perfectly valid, common choice here.
            int n; try{n=Integer.parseInt(entered.replaceAll("[^0-9]",""));}catch(NumberFormatException e){n=-1;}
            int limit=entered.isEmpty()?-1:n;
            s.pendingWidgetCharacterLimit=limit;
            Bukkit.getScheduler().runTask(plugin,()->renderWidgetToggles(p,s)); return;
        }
        if("widget-text".equals(mode)){
            Integer wi=s.widgetIndex;
            if(wi!=null&&wi<s.chunks.size()&&s.chunks.get(wi).kind==Kind.WIDGET){
                Chunk widget=s.chunks.get(wi);
                String sanitized=sanitizeWidgetText(entered,widget);
                if(!sanitized.isBlank())widget.widgetContents.add(new Chunk(Kind.TEXT,sanitized));
                resyncWidget(widget);
            }
            int reopen=wi==null?-1:wi;
            Bukkit.getScheduler().runTask(plugin,()->openWidgetContents(p,reopen)); return;
        }
        // Same reasoning as sanitizeWidgetText: a plain text chunk must never
        // be able to smuggle in literal widget/chars tag text.
        String plain=TemplateMarkers.stripTagText(entered);
        if(!plain.isBlank())s.chunks.add(new Chunk(Kind.TEXT,plain));
        Bukkit.getScheduler().runTask(plugin,()->openEditor(p));
    }
    /**
     * Strips inline color codes/tags (if {@code widget.widgetColors} is
     * off) and {@code %placeholder%} tokens (if {@code widget.widgetPlaceholders}
     * is off) out of text a player typed into a widget's Text option — see
     * "If colors are not allowed in that slot, strip any colors the user
     * adds through a text item. Do the same for placeholders."
     *
     * <p>{@code widget.widgetCharacterLimit} is enforced against the
     * <em>parsed</em> (visible-on-screen) character count — the same
     * count {@link afx.customplayernametags.format.NametagFormatter#plainText}
     * measures for the real nametag — rather than {@code out}'s raw
     * string length, so a color code like {@code &c} (2 raw characters,
     * 0 visible ones) doesn't eat into a player's actual typing room.
     * Truncation itself likewise cuts on visible characters, keeping
     * whatever color/style was applied to each kept character intact,
     * and — same as every other truncation in the plugin, now that a
     * {@code "..."} indicator is never counted against the limit it
     * signals — gets the same plain white {@code "..."} appended as any
     * other over-limit widget content, gated behind the same {@code
     * nametag-widget-truncate-indicator} setting
     * ({@link afx.customplayernametags.config.ConfigManager#isWidgetTruncationEllipsisEnabled()})
     * that already controls it for a widget's Placeholder-derived content.
     * A Text item typed in over the limit is therefore visibly marked as
     * cut off exactly like one that only became too long once a
     * Placeholder resolved, instead of being silently shortened with no
     * indication anything was lost.
     */
    private String sanitizeWidgetText(String text, Chunk widget) {
        // Widgets/Characters are plain tag text now rather than unprintable
        // codepoints, so they're typeable — stripped here so a player can't
        // hand-craft or break one from inside a widget's own Text option.
        String out=TemplateMarkers.stripTagText(text);
        if(!widget.widgetColors)out=INLINE_COLOR.matcher(out).replaceAll("");
        if(!widget.widgetPlaceholders)out=INLINE_PLACEHOLDER.matcher(out).replaceAll("");
        if(widget.widgetCharacterLimit>=0){
            var asComponent=afx.customplayernametags.format.NametagFormatter.toComponent(afx.customplayernametags.format.NametagFormatter.toMiniMessageSource(out));
            if(afx.customplayernametags.format.NametagFormatter.plainText(asComponent).length()>widget.widgetCharacterLimit){
                var truncated=config.isWidgetTruncationEllipsisEnabled()
                        ?afx.customplayernametags.format.NametagFormatter.truncateLineWithEllipsis(asComponent,widget.widgetCharacterLimit)
                        :afx.customplayernametags.format.NametagFormatter.truncateVisibleCharacters(asComponent,widget.widgetCharacterLimit);
                out=afx.customplayernametags.format.NametagFormatter.serialize(truncated);
            }
        }
        return out;
    }
    private void restoreTemporarySign(Session s){if(s.temporarySign!=null){s.temporarySign.update(true,false);s.temporarySign=null;}s.awaitingSign=false;}
    /**
     * Blocks any drag that touches one of this plugin's own menus. Clicks are
     * already cancelled in {@link #handleInventoryClick}, but a drag is a
     * separate event — without this a player could drag an item from their
     * own inventory into a menu slot, and it would be destroyed with the
     * menu the moment it closed.
     */
    public void handleInventoryDrag(InventoryDragEvent e) {
        if(!(e.getWhoClicked() instanceof Player p)||!(e.getView().getTopInventory().getHolder() instanceof Holder h)||!h.player.equals(p.getUniqueId()))return;
        int topSize=e.getView().getTopInventory().getSize();
        for(int slot:e.getRawSlots()){ if(slot<topSize){e.setCancelled(true);return;} }
    }
    public void handleInventoryClick(InventoryClickEvent e) {
        if(!(e.getWhoClicked() instanceof Player p)||!(e.getView().getTopInventory().getHolder() instanceof Holder h)||!h.player.equals(p.getUniqueId()))return;
        e.setCancelled(true); int slot=e.getRawSlot(); if(slot<0||slot>=e.getView().getTopInventory().getSize())return;
        if(h.view==View.ADMIN){
            if(slot==guiConfig.slot("admin-menu","global",11)){
                if(config.isSeparateBedrockGlobalFormatEnabled())openGlobalPlatformChoice(p);
                else begin(p,config.getNametagFormat(),Target.GLOBAL,"global");
            }
            else if(slot==guiConfig.slot("admin-menu","player",13))openPlayers(p);
            else if(slot==guiConfig.slot("admin-menu","groups",15)){
                if(config.isSeparateBedrockGroupFormatsEnabled())openGroupsPlatformChoice(p);
                else openGroups(p,false);
            }
            else if(slot==guiConfig.slot("admin-menu","close",22))p.closeInventory();
            return;
        }
        if(h.view==View.GLOBAL_PLATFORM_CHOICE){
            if(slot==guiConfig.slot("platform-choice-menu","java",11)){begin(p,config.getNametagFormat(),Target.GLOBAL,"global",false);return;}
            if(slot==guiConfig.slot("platform-choice-menu","bedrock",15)){begin(p,config.getBedrockGlobalFormat(),Target.GLOBAL,"global",true);return;}
            if(slot==guiConfig.slot("platform-choice-menu","back",22)){openAdminGui(p);return;}
            return;
        }
        if(h.view==View.GROUPS_PLATFORM_CHOICE){
            if(slot==guiConfig.slot("groups-platform-choice-menu","java",11)){openGroups(p,false);return;}
            if(slot==guiConfig.slot("groups-platform-choice-menu","bedrock",15)){openGroups(p,true);return;}
            if(slot==guiConfig.slot("groups-platform-choice-menu","back",22)){openAdminGui(p);return;}
            return;
        }
        if(h.view==View.PLAYERS){
            int back=guiConfig.slot("players-menu","back",53);
            if(slot==back){openAdminGui(p);return;}
            // Resolved from the clicked head itself rather than by re-indexing
            // Bukkit.getOnlinePlayers(): if anyone logs out between this menu
            // being drawn and being clicked, every later slot shifts by one and
            // position-based lookup would silently open the WRONG player's format.
            if(slot<back){
                Player q=playerFromHead(e.getView().getTopInventory().getItem(slot));
                if(q!=null)begin(p,plugin.getPlayerFormatStore().get(q.getUniqueId()),Target.PLAYER,q.getUniqueId().toString());
            }
            return;
        }
        if(h.view==View.GROUPS){
            boolean bedrock=h.selected==1;
            int back=guiConfig.slot("groups-menu","back",26);
            if(slot==back){openAdminGui(p);return;}
            List<String> all=manager.getGroupFormatStore().getGroupNames(bedrock);
            if(slot<back&&slot<all.size())begin(p,manager.getGroupFormatStore().get(all.get(slot),bedrock),Target.GROUP,all.get(slot),bedrock);
            return;
        }
        if(h.view==View.MAIN) {
            boolean hidden=manager.hasNametagsHidden(p.getUniqueId());
            if(slot==guiConfig.slot("main-menu","edit",11)){begin(p,manager.getEffectiveRawFormat(p),Target.PLAYER_EDIT,p.getUniqueId().toString());return;}
            if(slot==guiConfig.slot("main-menu","view",13)){sendCurrentFormat(p);p.closeInventory();return;}
            if(slot==guiConfig.slot("main-menu",hidden?"toggle-hidden":"toggle-visible",15)){boolean nowHidden=manager.toggleNametagsHidden(p);messages.send(p,nowHidden?"toggle-hidden":"toggle-shown");openMainMenu(p);return;}
            if(slot==guiConfig.slot("main-menu","close",22)){p.closeInventory();return;}
            return;
        }
        Session s=sessions.get(p.getUniqueId()); if(s==null)return;
        if(h.view==View.EDITOR) {
            Integer index=s.displayed.get(slot);
            if(index!=null){
                Chunk clicked=s.chunks.get(index);
                if(clicked.kind==Kind.WIDGET){openDetail(p,index);return;}
                // Non-Widget chunks are entirely read-only for a player editing their own applied
                // format (Target.PLAYER_EDIT) unless they're an admin — Widgets are the only piece
                // of an admin-authored format a plain player can ever click into.
                if(lockedForPlayer(p,s))return;
                openDetail(p,index);return;
            }
            List<Row> rows=computeRows(s);
            int maxScrollRow=Math.max(0,rows.size()-VISIBLE_ROWS);
            int maxLineLength=0; for(Row r:rows) maxLineLength=Math.max(maxLineLength,r.indices().size());
            int maxScrollCol=Math.max(0,maxLineLength-ROW_WIDTH);
            if(slot==guiConfig.slot("editor","back",45)){backFromEditor(p,s);return;}
            if(slot==guiConfig.slot("editor","create",53)){confirm(p,s);return;}
            if(slot==guiConfig.slot("editor","add-item",49)){if(!lockedForPlayer(p,s))openAddItemGui(p);return;}
            if(slot==guiConfig.slot("editor","scroll-up",48)){if(s.scrollRow>0){s.scrollRow--;openEditor(p);}return;}
            if(slot==guiConfig.slot("editor","scroll-down",50)){if(s.scrollRow<maxScrollRow){s.scrollRow++;openEditor(p);}return;}
            if(slot==guiConfig.slot("editor","move-left",47)){if(s.scrollCol>0){s.scrollCol--;openEditor(p);}return;}
            if(slot==guiConfig.slot("editor","move-right",51)){if(s.scrollCol<maxScrollCol){s.scrollCol++;openEditor(p);}return;}
            return;
        }
        if(h.view==View.ADD_ITEM) {
            if(slot==guiConfig.slot("add-item-menu","color",9)){openColors(p);return;}
            if(slot==guiConfig.slot("add-item-menu","placeholder",11)){openPlaceholders(p);return;}
            if(slot==guiConfig.slot("add-item-menu","text",13)){openTextChunkSign(p,s);return;}
            if(slot==guiConfig.slot("add-item-menu","newline",15)) {
                s.chunks.add(new Chunk(Kind.NEWLINE,"\\n"));openEditor(p);return;
            }
            // Widget is only ever placeable from the actual admin editor — a player editing their
            // own applied format (Target.PLAYER_EDIT) never sees this button in the first place
            // (see openAddItemGui).
            if(s.target!=Target.PLAYER_EDIT&&slot==guiConfig.slot("add-item-menu","widget",17)){openWidgetToggles(p);return;}
            if(slot==guiConfig.slot("add-item-menu","back",22)){openEditor(p);return;}
            return;
        }
        if(h.view==View.DETAIL) {
            int i=h.selected; if(i<0||i>=s.chunks.size()){openEditor(p);return;}
            Chunk selected=s.chunks.get(i);
            if(selected.kind==Kind.WIDGET&&slot==guiConfig.slot("detail-menu","edit",13)){openWidgetContents(p,i);return;}
            if(lockedForPlayer(p,s))return;
            // Widgets deliberately have no Delete button on this page (see openDetail).
            if(selected.kind!=Kind.WIDGET&&slot==guiConfig.slot("detail-menu","delete",13)){openConfirmChunkDelete(p,i);return;}
            // Never swap across a NEWLINE chunk — that would move this item into the previous/next
            // line instead of just repositioning it within its own line.
            if(slot==guiConfig.slot("detail-menu","move-left",11)&&i>0&&s.chunks.get(i-1).kind!=Kind.NEWLINE){Collections.swap(s.chunks,i,i-1);openDetail(p,i-1);return;}
            if(slot==guiConfig.slot("detail-menu","move-right",15)&&i<s.chunks.size()-1&&s.chunks.get(i+1).kind!=Kind.NEWLINE){Collections.swap(s.chunks,i,i+1);openDetail(p,i+1);return;}
            if(slot==guiConfig.slot("detail-menu","back",22))openEditor(p); return;
        }
        if(h.view==View.CONFIRM_DELETE_CHUNK) {
            int i=h.selected;
            if(slot==guiConfig.slot("confirm-menu","confirm",15)){
                if(i>=0&&i<s.chunks.size())s.chunks.remove(i);
                openEditor(p);return;
            }
            if(slot==guiConfig.slot("confirm-menu","cancel",11)){
                if(i>=0&&i<s.chunks.size())openDetail(p,i); else openEditor(p);
                return;
            }
            return;
        }
        if(h.view==View.PLACEHOLDERS) {
            List<EditorPlaceholderStore.Placeholder> all=placeholders.getAll();
            int back=guiConfig.slot("placeholders-menu","back",26);
            // Back returns to the "Add Format Piece" menu this was opened from, not straight past it
            // to the chunk editor.
            if(slot==back){openAddItemGui(p);return;}
            if(slot==0){s.chunks.add(new Chunk(Kind.PLACEHOLDER,"{player}"));openEditor(p);return;}
            int idx=slot-1;
            if(idx>=0&&idx<back&&idx<all.size()){s.chunks.add(new Chunk(Kind.PLACEHOLDER,all.get(idx).value()));openEditor(p);}
            return;
        }
        if(h.view==View.COLORS) {
            int back=guiConfig.slot("colors-menu","back",26);
            String color=null;
            for(ColorChoice c:COLOR_CHOICES){ if(slot==guiConfig.slot("colors-menu",c.key(),c.fallbackSlot())){color=c.tag();break;} }
            // Back returns to the "Add Format Piece" menu this was opened from, not straight past it
            // to the chunk editor.
            if(color!=null){s.chunks.add(new Chunk(Kind.COLOR,color));openEditor(p);} else if(slot==back)openAddItemGui(p);
            return;
        }
        if(h.view==View.WIDGET_TOGGLES){
            if(slot==guiConfig.slot("widget-toggles-menu","colors",10)){s.pendingWidgetColors=!s.pendingWidgetColors;renderWidgetToggles(p,s);return;}
            if(slot==guiConfig.slot("widget-toggles-menu","placeholders",12)){s.pendingWidgetPlaceholders=!s.pendingWidgetPlaceholders;renderWidgetToggles(p,s);return;}
            if(slot==guiConfig.slot("widget-toggles-menu","text",14)){s.pendingWidgetText=!s.pendingWidgetText;renderWidgetToggles(p,s);return;}
            if(slot==guiConfig.slot("widget-toggles-menu","character-limit",16)){openNumberSign(p,s,"widget-character-limit");return;}
            if(slot==guiConfig.slot("widget-toggles-menu","add",22)){
                if(s.widgetIndex!=null){
                    Chunk widget=s.chunks.get(s.widgetIndex);
                    widget.widgetColors=s.pendingWidgetColors; widget.widgetPlaceholders=s.pendingWidgetPlaceholders; widget.widgetText=s.pendingWidgetText;
                    widget.widgetCharacterLimit=s.pendingWidgetCharacterLimit;
                    resyncWidget(widget);
                    int index=s.widgetIndex;
                    openWidgetContents(p,index); return;
                }
                Chunk widget=new Chunk(Kind.WIDGET,"");
                widget.widgetId=TemplateMarkers.generateWidgetId();
                widget.widgetColors=s.pendingWidgetColors; widget.widgetPlaceholders=s.pendingWidgetPlaceholders; widget.widgetText=s.pendingWidgetText;
                widget.widgetCharacterLimit=s.pendingWidgetCharacterLimit;
                widget.widgetContents=new ArrayList<>();
                resyncWidget(widget);
                s.chunks.add(widget);
                openEditor(p); return;
            }
            if(slot==guiConfig.slot("widget-toggles-menu","back",26)){
                if(s.widgetIndex!=null)openWidgetContents(p,s.widgetIndex); else openAddItemGui(p);
                return;
            }
            return;
        }
        if(h.view==View.WIDGET_CONTENTS){
            if(s.widgetIndex==null||s.widgetIndex>=s.chunks.size()||s.chunks.get(s.widgetIndex).kind!=Kind.WIDGET){s.widgetIndex=null;openEditor(p);return;}
            Chunk widget=s.chunks.get(s.widgetIndex);
            // Any player can move/delete/edit an item already inside a widget (not just fill an
            // empty slot via "Add Item" below) — including items placed there by someone else.
            if(slot<9&&slot<widget.widgetContents.size()){openWidgetItemDetail(p,slot);return;}
            if(slot==guiConfig.slot("widget-contents-menu","add-item",13)){openWidgetAddItem(p);return;}
            if(slot==guiConfig.slot("widget-contents-menu","edit-permissions",11)&&s.target!=Target.PLAYER_EDIT){openWidgetPermissions(p,s.widgetIndex);return;}
            if(slot==guiConfig.slot("widget-contents-menu","delete-widget",15)&&s.target!=Target.PLAYER_EDIT){
                openConfirmWidgetDelete(p,s.widgetIndex); return;
            }
            if(slot==guiConfig.slot("widget-contents-menu","back",22)){int index=s.widgetIndex;s.widgetIndex=null;openDetail(p,index);return;}
            return;
        }
        if(h.view==View.CONFIRM_DELETE_WIDGET){
            int i=h.selected;
            if(slot==guiConfig.slot("confirm-menu","confirm",15)){
                if(i>=0&&i<s.chunks.size()&&s.chunks.get(i).kind==Kind.WIDGET)s.chunks.remove(i);
                s.widgetIndex=null; openEditor(p); return;
            }
            if(slot==guiConfig.slot("confirm-menu","cancel",11)){
                if(i>=0&&i<s.chunks.size()&&s.chunks.get(i).kind==Kind.WIDGET)openWidgetContents(p,i); else{s.widgetIndex=null;openEditor(p);}
                return;
            }
            return;
        }
        if(h.view==View.WIDGET_ITEM_DETAIL){
            if(s.widgetIndex==null||s.widgetIndex>=s.chunks.size()||s.chunks.get(s.widgetIndex).kind!=Kind.WIDGET){s.widgetIndex=null;openEditor(p);return;}
            Chunk widget=s.chunks.get(s.widgetIndex); int i=h.selected;
            if(slot==guiConfig.slot("widget-item-detail-menu","move-left",11)&&i>0){Collections.swap(widget.widgetContents,i,i-1);resyncWidget(widget);openWidgetItemDetail(p,i-1);return;}
            if(slot==guiConfig.slot("widget-item-detail-menu","move-right",15)&&i<widget.widgetContents.size()-1){Collections.swap(widget.widgetContents,i,i+1);resyncWidget(widget);openWidgetItemDetail(p,i+1);return;}
            if(slot==guiConfig.slot("widget-item-detail-menu","delete",13)){
                if(i>=0&&i<widget.widgetContents.size()){widget.widgetContents.remove(i);resyncWidget(widget);}
                openWidgetContents(p,s.widgetIndex); return;
            }
            if(slot==guiConfig.slot("widget-item-detail-menu","back",22)){openWidgetContents(p,s.widgetIndex);return;}
            return;
        }
        if(h.view==View.WIDGET_ADD_ITEM){
            if(s.widgetIndex==null||s.widgetIndex>=s.chunks.size()||s.chunks.get(s.widgetIndex).kind!=Kind.WIDGET){s.widgetIndex=null;openEditor(p);return;}
            Chunk widget=s.chunks.get(s.widgetIndex);
            if(widget.widgetColors&&slot==guiConfig.slot("widget-add-item-menu","color",11)){openWidgetColors(p);return;}
            if(widget.widgetPlaceholders&&slot==guiConfig.slot("widget-add-item-menu","placeholder",13)){openWidgetPlaceholders(p);return;}
            if(widget.widgetText&&slot==guiConfig.slot("widget-add-item-menu","text",15)){openWidgetTextSign(p,s);return;}
            if(slot==guiConfig.slot("widget-add-item-menu","back",22)){openWidgetContents(p,s.widgetIndex);return;}
            return;
        }
        if(h.view==View.WIDGET_COLORS){
            if(s.widgetIndex==null||s.widgetIndex>=s.chunks.size()||s.chunks.get(s.widgetIndex).kind!=Kind.WIDGET){s.widgetIndex=null;openEditor(p);return;}
            Chunk widget=s.chunks.get(s.widgetIndex);
            int back=guiConfig.slot("colors-menu","back",26); String color=null;
            for(ColorChoice c:COLOR_CHOICES){ if(slot==guiConfig.slot("colors-menu",c.key(),c.fallbackSlot())){color=c.tag();break;} }
            if(color!=null){widget.widgetContents.add(new Chunk(Kind.COLOR,color));resyncWidget(widget);openWidgetContents(p,s.widgetIndex);}
            else if(slot==back)openWidgetContents(p,s.widgetIndex);
            return;
        }
        if(h.view==View.WIDGET_PLACEHOLDERS){
            if(s.widgetIndex==null||s.widgetIndex>=s.chunks.size()||s.chunks.get(s.widgetIndex).kind!=Kind.WIDGET){s.widgetIndex=null;openEditor(p);return;}
            Chunk widget=s.chunks.get(s.widgetIndex);
            List<EditorPlaceholderStore.Placeholder> all=placeholders.getAll();
            int back=guiConfig.slot("placeholders-menu","back",26);
            if(slot==back){openWidgetContents(p,s.widgetIndex);return;}
            if(slot==0){widget.widgetContents.add(new Chunk(Kind.PLACEHOLDER,"{player}"));resyncWidget(widget);openWidgetContents(p,s.widgetIndex);return;}
            int idx=slot-1;
            if(idx>=0&&idx<back&&idx<all.size()){widget.widgetContents.add(new Chunk(Kind.PLACEHOLDER,all.get(idx).value()));resyncWidget(widget);openWidgetContents(p,s.widgetIndex);}
            return;
        }
    }
    /** The online player whose name is on {@code head}, or {@code null} if there isn't one (empty slot, or they logged off since the menu was drawn). */
    private static Player playerFromHead(ItemStack head){
        if(head==null)return null;
        ItemMeta meta=head.getItemMeta();
        if(meta==null||!meta.hasDisplayName())return null;
        String name=ChatColor.stripColor(meta.getDisplayName());
        return name==null||name.isEmpty()?null:Bukkit.getPlayerExact(name);
    }
    public void handleClose(Player p, Inventory inventory) {
        if(!(inventory.getHolder() instanceof Holder h)||!h.player.equals(p.getUniqueId()))return;
        // Opening the sign editor closes this inventory; keep the session until the sign is submitted.
        Bukkit.getScheduler().runTask(plugin,()->{Session s=sessions.get(p.getUniqueId());if(s!=null&&!s.awaitingSign&&!(p.getOpenInventory().getTopInventory().getHolder() instanceof Holder n&&n.player.equals(p.getUniqueId())))sessions.remove(p.getUniqueId());});
    }
    /**
     * Gateway into the chunk editor for every entry point (global/player/group format,
     * or a brand-new preset).
     */
    private void begin(Player p,String raw,Target target,String id){
        begin(p,raw,target,id,false);
    }
    private void begin(Player p,String raw,Target target,String id,boolean bedrock){
        Session s=new Session(raw,target,id); s.bedrock=bedrock;
        sessions.put(p.getUniqueId(),s);openEditor(p);
    }
    /**
     * The editor's "Back" button: discards the in-progress (unsaved)
     * session and returns to whichever menu originally opened the editor
     * for {@code s.target} — the admin menu for a global-format edit, the
     * player/group picker for a player/group-format edit, or the main
     * {@code /nametag} menu for a player editing their own applied format.
     */
    private void backFromEditor(Player p, Session s){
        boolean bedrock=s.bedrock;
        sessions.remove(p.getUniqueId());
        switch(s.target){
            case GLOBAL -> openAdminGui(p);
            case PLAYER -> openPlayers(p);
            case GROUP -> openGroups(p,bedrock);
            case PLAYER_EDIT -> openMainMenu(p);
        }
    }
    private void openEditor(Player p) {
        Session s=sessions.get(p.getUniqueId());if(s==null)return; s.displayed.clear();
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.EDITOR,-1),54,guiConfig.title("editor",ChatColor.DARK_BLUE+"Nametag Editor"));
        List<Row> rows=computeRows(s);
        // Clamp in case chunks were removed (or the format got shorter) since the last time this player scrolled.
        int maxScrollRow=Math.max(0,rows.size()-VISIBLE_ROWS);
        if(s.scrollRow>maxScrollRow)s.scrollRow=maxScrollRow; if(s.scrollRow<0)s.scrollRow=0;
        int maxLineLength=0; for(Row r:rows) maxLineLength=Math.max(maxLineLength,r.indices().size());
        int maxScrollCol=Math.max(0,maxLineLength-ROW_WIDTH);
        if(s.scrollCol>maxScrollCol)s.scrollCol=maxScrollCol; if(s.scrollCol<0)s.scrollCol=0;
        renderChunks(p,inv,s,rows);
        put(inv,guiConfig.button("editor","back",45,Material.OAK_DOOR,"&eBack","&7Discard changes"));
        put(inv,guiConfig.button("editor","create",53,Material.EMERALD,"&aCreate","&7Save format"));
        // A player editing their own applied format (Target.PLAYER_EDIT) can't add new top-level
        // chunks at all — only fill widgets an admin already placed — so the button is hidden
        // entirely rather than shown-but-blocked.
        if(!lockedForPlayer(p,s)) put(inv,guiConfig.button("editor","add-item",49,Material.HOPPER,"&aAdd Item","&7Add a new format piece"));
        // Vertical scroll (rows beyond the 5 visible) — immediate left/right of the Add Item button.
        if(rows.size()>VISIBLE_ROWS) {
            boolean canUp=s.scrollRow>0, canDown=s.scrollRow<maxScrollRow;
            GuiConfigManager.Button up=guiConfig.button("editor","scroll-up",48,Material.SPECTRAL_ARROW,"&eScroll Up");
            GuiConfigManager.Button down=guiConfig.button("editor","scroll-down",50,Material.SPECTRAL_ARROW,"&eScroll Down");
            String range="Rows "+(s.scrollRow+1)+"-"+Math.min(rows.size(),s.scrollRow+VISIBLE_ROWS)+" of "+rows.size();
            inv.setItem(up.slot(),item(up.material(),(canUp?ChatColor.YELLOW:ChatColor.DARK_GRAY)+ChatColor.stripColor(up.name()),ChatColor.GRAY+range));
            inv.setItem(down.slot(),item(down.material(),(canDown?ChatColor.YELLOW:ChatColor.DARK_GRAY)+ChatColor.stripColor(down.name()),ChatColor.GRAY+range));
        }
        // Horizontal scroll (a single line longer than 9 chunks) — immediate left/right of the vertical-scroll buttons.
        if(maxScrollCol>0) {
            boolean canLeft=s.scrollCol>0, canRight=s.scrollCol<maxScrollCol;
            GuiConfigManager.Button left=guiConfig.button("editor","move-left",47,Material.ARROW,"&eMove Left","&7Scroll this line left");
            GuiConfigManager.Button right=guiConfig.button("editor","move-right",51,Material.ARROW,"&eMove Right","&7Scroll this line right");
            String cols="Columns "+(s.scrollCol+1)+"-"+Math.min(maxLineLength,s.scrollCol+ROW_WIDTH)+" of "+maxLineLength;
            List<String> leftLore=new ArrayList<>(left.lore()); leftLore.add(ChatColor.GRAY+cols);
            List<String> rightLore=new ArrayList<>(right.lore()); rightLore.add(ChatColor.GRAY+cols);
            inv.setItem(left.slot(),item(left.material(),(canLeft?ChatColor.YELLOW:ChatColor.DARK_GRAY)+ChatColor.stripColor(left.name()),leftLore.toArray(new String[0])));
            inv.setItem(right.slot(),item(right.material(),(canRight?ChatColor.YELLOW:ChatColor.DARK_GRAY)+ChatColor.stripColor(right.name()),rightLore.toArray(new String[0])));
        }
        p.openInventory(inv);
    }
    /** Whether {@code p} only has read/widget-fill access to {@code s} — true for a non-admin player editing their own applied format (Target.PLAYER_EDIT), false for every other session and for any admin. */
    private boolean lockedForPlayer(Player p, Session s) {
        return s.target==Target.PLAYER_EDIT && !p.hasPermission("customplayernametags.admin");
    }
    /** Splits the format's chunks into logical lines (split on newline chunks). No longer wrapped across extra display rows — a line longer than one row scrolls horizontally instead (see {@link Session#scrollCol}). */
    private List<Row> computeRows(Session s) {
        List<List<Integer>> logical=new ArrayList<>(); logical.add(new ArrayList<>());
        for(int i=0;i<s.chunks.size();i++){ if(s.chunks.get(i).kind==Kind.NEWLINE){List<Integer> next=new ArrayList<>();next.add(i);logical.add(next);}else logical.get(logical.size()-1).add(i); }
        List<Row> rows=new ArrayList<>();
        for(List<Integer> line:logical) rows.add(new Row(line));
        return rows;
    }
    /** Renders one screen's worth of logical lines — rows s.scrollRow through s.scrollRow+VISIBLE_ROWS-1 — each windowed horizontally to chunks s.scrollCol through s.scrollCol+8. */
    private void renderChunks(Player p,Inventory inv,Session s,List<Row> rows) {
        boolean interactive=!lockedForPlayer(p,s);
        for(int r=0;r<VISIBLE_ROWS;r++) {
            int rowIndex=s.scrollRow+r; if(rowIndex>=rows.size())break;
            List<Integer> line=rows.get(rowIndex).indices();
            int take=Math.max(0,Math.min(ROW_WIDTH,line.size()-s.scrollCol));
            for(int n=0;n<take;n++){int index=line.get(s.scrollCol+n);int slot=r*9+n;s.displayed.put(slot,index);inv.setItem(slot,chunkItem(p,s.chunks.get(index),interactive));}
        }
    }
    /**
     * Opens the "Edit {Kind}" page for chunk {@code index}: the top row
     * (slots 0-8) is the chunk's whole logical line — every other chunk on
     * that same line, windowed around this one if the line is longer than 9
     * — rendered as plain, tooltip-less items (see {@link #chunkPreviewItem})
     * with the chunk actually being edited marked with arrows. Because
     * Move left/right physically swap this chunk with its neighbor in
     * {@code s.chunks} and then reopen this same page, the item visibly
     * slides over by one slot rather than the move being purely abstract.
     */
    private void openDetail(Player p,int index) {
        Session s=sessions.get(p.getUniqueId());if(s==null)return; Chunk c=s.chunks.get(index);
        String kindLabel=titleCase(c.kind.name());
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.DETAIL,index),27,guiConfig.title("detail-menu",ChatColor.DARK_BLUE+"Edit "+kindLabel).replace("{kind}",kindLabel));
        renderDetailRow(p,inv,s,index);
        put(inv,guiConfig.button("detail-menu","move-left",11,Material.ARROW,"&eMove left","&7Move earlier in the format"));
        // A Widget shows "Edit Contents" in the middle slot instead of Delete:
        // the widget can already be deleted from inside its own contents page
        // (widget-contents-menu's "Delete Widget"), so a second delete button
        // here would be redundant.
        if(c.kind==Kind.WIDGET) put(inv,guiConfig.button("detail-menu","edit",13,Material.ITEM_FRAME,"&eEdit Contents","&7View and edit this widget's contents"));
        else put(inv,guiConfig.button("detail-menu","delete",13,Material.BARRIER,"&cDelete","&7Remove this chunk"));
        put(inv,guiConfig.button("detail-menu","move-right",15,Material.ARROW,"&eMove right","&7Move later in the format"));
        put(inv,guiConfig.button("detail-menu","back",22,Material.OAK_DOOR,"&aBack"));
        p.openInventory(inv);
    }
    /** Confirmation page opened by the detail-menu's Delete button — shows a bare preview of the chunk itself so it's clear what's about to be removed. */
    private void openConfirmChunkDelete(Player p,int index) {
        Session s=sessions.get(p.getUniqueId());if(s==null)return; Chunk c=s.chunks.get(index);
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.CONFIRM_DELETE_CHUNK,index),27,guiConfig.title("confirm-menu",ChatColor.DARK_BLUE+"Confirm Delete"));
        inv.setItem(4,chunkPreviewItem(p,c,false));
        put(inv,guiConfig.button("confirm-menu","confirm",15,Material.EMERALD_BLOCK,"&aConfirm","&7This cannot be undone"));
        put(inv,guiConfig.button("confirm-menu","cancel",11,Material.REDSTONE_BLOCK,"&cCancel"));
        p.openInventory(inv);
    }
    /** Renders the logical line containing chunk index {@code selected} across slots 0-8, windowed to keep {@code selected} visible if the line has more than 9 chunks. */
    private void renderDetailRow(Player p, Inventory inv, Session s, int selected) {
        List<Integer> line=null;
        for(Row r:computeRows(s)) if(r.indices().contains(selected)){line=r.indices();break;}
        if(line==null)return;
        int pos=line.indexOf(selected);
        int start=Math.max(0,Math.min(pos-ROW_WIDTH/2,Math.max(0,line.size()-ROW_WIDTH)));
        int take=Math.min(ROW_WIDTH,line.size()-start);
        for(int n=0;n<take;n++){
            int chunkIndex=line.get(start+n);
            inv.setItem(n,chunkPreviewItem(p,s.chunks.get(chunkIndex),chunkIndex==selected));
        }
    }
    /** A bare (no tooltip) rendering of one chunk for the detail-menu's context row — the item actually being edited is swapped to a nether star (regardless of its normal material) and bracketed with arrows, since there's no lore here to say which one it is. */
    private ItemStack chunkPreviewItem(Player p, Chunk c, boolean selected){
        ItemStack result=chunkItem(p,c,true); ItemMeta meta=result.getItemMeta();
        String name=meta.getDisplayName();
        if(selected){
            result=new ItemStack(Material.NETHER_STAR); meta=result.getItemMeta();
            meta.setDisplayName(ChatColor.YELLOW+"» "+name+ChatColor.YELLOW+" «");
        }
        meta.setLore(null);
        result.setItemMeta(meta); return result;
    }
    /** {@code "TEXT"} -> {@code "Text"} — used so the detail-menu title reads naturally instead of shouting the chunk kind's raw enum name. */
    private static String titleCase(String s){ return s.isEmpty()?s:Character.toUpperCase(s.charAt(0))+s.substring(1).toLowerCase(Locale.ROOT); }
    /**
     * The "Add Item" sub-menu opened from the editor's middle bottom
     * button: the 4 ways any session can add a new chunk (color,
     * placeholder, text, newline), plus — only for an admin actually
     * editing a Global/Player/Group template, never a player editing their
     * own applied format — Widget, the one template-only item kind. See
     * {@link TemplateMarkers}.
     */
    private void openAddItemGui(Player p) {
        Session s=sessions.get(p.getUniqueId());if(s==null)return;
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.ADD_ITEM,-1),27,guiConfig.title("add-item-menu",ChatColor.DARK_BLUE+"Add Format Item"));
        put(inv,guiConfig.button("add-item-menu","color",9,Material.RED_WOOL,"&cColor","&7Add a colour/style chunk"));
        put(inv,guiConfig.button("add-item-menu","placeholder",11,Material.NAME_TAG,"&bPlaceholder","&7Add a saved placeholder"));
        put(inv,guiConfig.button("add-item-menu","text",13,Material.OAK_SIGN,"&fText","&7Add text via sign GUI"));
        put(inv,guiConfig.button("add-item-menu","newline",15,Material.FEATHER,"&aNew Line","&7Add a newline chunk"));
        if(s.target!=Target.PLAYER_EDIT){
            put(inv,guiConfig.button("add-item-menu","widget",17,Material.ITEM_FRAME,"&dWidget","&7Add a slot players can fill themselves"));
        }
        put(inv,guiConfig.button("add-item-menu","back",22,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    private void openPlaceholders(Player p){
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.PLACEHOLDERS,-1),27,guiConfig.title("placeholders-menu",ChatColor.DARK_BLUE+"Select Placeholder"));
        inv.setItem(0,usernamePlaceholderItem(p));
        int back=guiConfig.slot("placeholders-menu","back",26);
        int i=1;for(var x:placeholders.getAll()){if(i>=back)break;inv.setItem(i++,placeholderItem(p,x));}
        put(inv,guiConfig.button("placeholders-menu","back",26,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    /**
     * Fixed entry pinned at slot 0 of both placeholder pickers ({@link #openPlaceholders}
     * and {@link #openWidgetPlaceholders}) — inserts the plugin's own built-in
     * {@code {player}} token (resolved to whichever player is actually wearing the
     * nametag at render time), not a PlaceholderAPI {@code %...%} placeholder.
     */
    private ItemStack usernamePlaceholderItem(Player p){
        ItemStack result=new ItemStack(Material.PLAYER_HEAD); ItemMeta meta=result.getItemMeta();
        meta.setDisplayName(ChatColor.AQUA+"Username");
        meta.setLore(List.of(ChatColor.GRAY+"{player}",ChatColor.GRAY+"Click to add — e.g. "+p.getName()));
        result.setItemMeta(meta); return result;
    }
    /**
     * Builds the item shown for one configured editor placeholder: its
     * display name is the placeholder's tooltip title (an admin-set name, or
     * the placeholder's key if none was set — see
     * {@link EditorPlaceholderStore.Placeholder#displayTitle()}), and its
     * lore is the placeholder's value parsed exactly as {@code p} would
     * currently see it — so a player picking a placeholder can see up front
     * what it'll actually look like for them, not just its raw {@code %...%}
     * form.
     */
    private ItemStack placeholderItem(Player p, EditorPlaceholderStore.Placeholder placeholder){
        ItemStack result=new ItemStack(Material.NAME_TAG); ItemMeta meta=result.getItemMeta();
        meta.setDisplayName(ChatColor.AQUA+placeholder.displayTitle());
        Component parsed=afx.customplayernametags.format.NametagFormatter.toComponent(manager.parseFormat(p,placeholder.value()));
        meta.lore(afx.customplayernametags.format.NametagFormatter.splitLines(parsed)); result.setItemMeta(meta); return result;
    }
    private void openColors(Player p){
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.COLORS,-1),27,guiConfig.title("colors-menu",ChatColor.DARK_BLUE+"Select Color"));
        for(ColorChoice c:COLOR_CHOICES){
            GuiConfigManager.Button b=guiConfig.button("colors-menu",c.key(),c.fallbackSlot(),c.fallbackMaterial(),c.fallbackName(),"&7Color/style — click to edit");
            inv.setItem(b.slot(),item(b.material(),b.name(),b.loreArray()));
        }
        put(inv,guiConfig.button("colors-menu","back",26,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    /** Opens the allowed-item-types toggle page for a brand-new Widget — admin-only, reached from Add Item's Widget button. {@code s.widgetIndex} is cleared so {@link #renderWidgetToggles} knows this is create-mode, not editing an existing widget's permissions (see {@link #openWidgetPermissions}). */
    private void openWidgetToggles(Player p){
        Session s=sessions.get(p.getUniqueId());if(s==null)return;
        s.widgetIndex=null;
        s.pendingWidgetColors=true; s.pendingWidgetPlaceholders=true; s.pendingWidgetText=true; s.pendingWidgetCharacterLimit=-1;
        renderWidgetToggles(p,s);
    }
    /** Opens the same allowed-item-types toggle page pre-filled with an existing widget's current settings — admin-only, reached from widget-contents-menu's "Edit Permissions" button. {@code s.widgetIndex} stays set to {@code index}, which is what tells {@link #renderWidgetToggles}'s "Add"/Back buttons to update that widget in place instead of creating a new one. */
    private void openWidgetPermissions(Player p, int index){
        Session s=sessions.get(p.getUniqueId());if(s==null)return;
        if(index<0||index>=s.chunks.size()||s.chunks.get(index).kind!=Kind.WIDGET){openEditor(p);return;}
        Chunk widget=s.chunks.get(index);
        s.widgetIndex=index;
        s.pendingWidgetColors=widget.widgetColors; s.pendingWidgetPlaceholders=widget.widgetPlaceholders;
        s.pendingWidgetText=widget.widgetText; s.pendingWidgetCharacterLimit=widget.widgetCharacterLimit;
        renderWidgetToggles(p,s);
    }
    private void renderWidgetToggles(Player p, Session s){
        boolean editingExisting=s.widgetIndex!=null;
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.WIDGET_TOGGLES,-1),27,guiConfig.title("widget-toggles-menu",ChatColor.DARK_BLUE+"Widget: Allowed Items"));
        // Slot/material/base-name come from gui.yml like every other button; the on/off
        // green-vs-red coloring and enabled/disabled lore are applied on top at render
        // time (same pattern as the editor's scroll-up/scroll-down buttons), so the
        // toggle's live state doesn't have to itself live in gui.yml.
        GuiConfigManager.Button colors=guiConfig.button("widget-toggles-menu","colors",10,Material.RED_WOOL,"&cAllow Colors","&7Whether colors/styles can be added to this widget");
        GuiConfigManager.Button placeholdersBtn=guiConfig.button("widget-toggles-menu","placeholders",12,Material.NAME_TAG,"&bAllow Placeholders","&7Whether placeholders can be added to this widget");
        GuiConfigManager.Button text=guiConfig.button("widget-toggles-menu","text",14,Material.OAK_SIGN,"&fAllow Text","&7Whether text can be added to this widget");
        inv.setItem(colors.slot(),toggleItem(colors.material(),ChatColor.stripColor(colors.name()),s.pendingWidgetColors));
        inv.setItem(placeholdersBtn.slot(),toggleItem(placeholdersBtn.material(),ChatColor.stripColor(placeholdersBtn.name()),s.pendingWidgetPlaceholders));
        inv.setItem(text.slot(),toggleItem(text.material(),ChatColor.stripColor(text.name()),s.pendingWidgetText));
        // Not a boolean toggle — clicking opens the sign editor (see openNumberSign/handleSignChange's
        // "widget-character-limit" mode) to type a new number, or blank for unlimited.
        GuiConfigManager.Button charLimit=guiConfig.button("widget-toggles-menu","character-limit",16,Material.PAPER,"&eCharacter Limit","&7Maximum characters allowed in a Text item added to this widget");
        List<String> charLimitLore=new ArrayList<>(charLimit.lore());
        charLimitLore.add(ChatColor.GRAY+"Current: "+(s.pendingWidgetCharacterLimit<0?"Unlimited":String.valueOf(s.pendingWidgetCharacterLimit)));
        inv.setItem(charLimit.slot(),item(charLimit.material(),charLimit.name(),charLimitLore.toArray(new String[0])));
        GuiConfigManager.Button add=guiConfig.button("widget-toggles-menu","add",22,Material.EMERALD,"&aAdd","&7Add this widget to the format");
        inv.setItem(add.slot(), editingExisting
                ?item(add.material(),ChatColor.GREEN+"Save Changes",ChatColor.GRAY+"Apply these settings to this widget")
                :item(add.material(),add.name(),add.loreArray()));
        put(inv,guiConfig.button("widget-toggles-menu","back",26,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    private static ItemStack toggleItem(Material m, String label, boolean on){
        return item(m,(on?ChatColor.GREEN:ChatColor.RED)+label,ChatColor.GRAY+(on?"Enabled — click to disable":"Disabled — click to enable"));
    }
    /** Opens the page showing what's currently inside widget chunk {@code index} — what every player (or, with the extra admin-only buttons, the admin) sees when they click a Widget item in the grid. */
    private void openWidgetContents(Player p, int index){
        Session s=sessions.get(p.getUniqueId());if(s==null)return;
        if(index<0||index>=s.chunks.size()||s.chunks.get(index).kind!=Kind.WIDGET){openEditor(p);return;}
        s.widgetIndex=index; Chunk widget=s.chunks.get(index);
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.WIDGET_CONTENTS,-1),27,guiConfig.title("widget-contents-menu",ChatColor.DARK_BLUE+"Widget Contents"));
        // Every player can click into an existing item's detail menu (move/edit/delete it), not just admins.
        for(int n=0;n<widget.widgetContents.size()&&n<9;n++)inv.setItem(n,chunkItem(p,widget.widgetContents.get(n),true));
        put(inv,guiConfig.button("widget-contents-menu","add-item",13,Material.HOPPER,"&aAdd Item","&7Add an item to this widget"));
        // Only shown to an admin actually editing a Global/Player/Group template — never to a
        // player filling in a widget slot on their own applied format.
        if(s.target!=Target.PLAYER_EDIT){
            put(inv,guiConfig.button("widget-contents-menu","edit-permissions",11,Material.COMPARATOR,"&eEdit Permissions","&7Change what item types are allowed here"));
            put(inv,guiConfig.button("widget-contents-menu","delete-widget",15,Material.BARRIER,"&cDelete Widget","&7Remove this widget entirely"));
        }
        put(inv,guiConfig.button("widget-contents-menu","back",22,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    /** Confirmation page opened by widget-contents-menu's Delete Widget button — shows a bare preview of the widget chunk itself so it's clear what's about to be removed, same shape as {@link #openConfirmChunkDelete}. */
    private void openConfirmWidgetDelete(Player p,int index) {
        Session s=sessions.get(p.getUniqueId());if(s==null)return; Chunk c=s.chunks.get(index);
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.CONFIRM_DELETE_WIDGET,index),27,guiConfig.title("confirm-menu",ChatColor.DARK_BLUE+"Confirm Delete"));
        inv.setItem(4,chunkPreviewItem(p,c,false));
        put(inv,guiConfig.button("confirm-menu","confirm",15,Material.EMERALD_BLOCK,"&aConfirm","&7This cannot be undone"));
        put(inv,guiConfig.button("confirm-menu","cancel",11,Material.REDSTONE_BLOCK,"&cCancel"));
        p.openInventory(inv);
    }
    /** The move-left/delete/edit/move-right page for one item inside a widget's contents — same shape as {@link #openDetail}, scoped to {@code widget.widgetContents} instead of the whole format. Open to any player; see the WIDGET_CONTENTS click handling in {@link #handleInventoryClick}. */
    private void openWidgetItemDetail(Player p, int subIndex){
        Session s=sessions.get(p.getUniqueId());if(s==null||s.widgetIndex==null)return;
        Chunk widget=s.chunks.get(s.widgetIndex);
        if(subIndex<0||subIndex>=widget.widgetContents.size()){openWidgetContents(p,s.widgetIndex);return;}
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.WIDGET_ITEM_DETAIL,subIndex),27,guiConfig.title("widget-item-detail-menu",ChatColor.DARK_BLUE+"Edit Widget Item"));
        inv.setItem(4,chunkPreviewItem(p,widget.widgetContents.get(subIndex),true));
        put(inv,guiConfig.button("widget-item-detail-menu","move-left",11,Material.ARROW,"&eMove left"));
        put(inv,guiConfig.button("widget-item-detail-menu","delete",13,Material.BARRIER,"&cDelete"));
        put(inv,guiConfig.button("widget-item-detail-menu","move-right",15,Material.ARROW,"&eMove right"));
        put(inv,guiConfig.button("widget-item-detail-menu","back",22,Material.OAK_DOOR,"&aBack"));
        p.openInventory(inv);
    }
    /** The "add an item to this widget" sub-menu — disabled item types remain visible as barriers so players can see what the widget does not permit. */
    private void openWidgetAddItem(Player p){
        Session s=sessions.get(p.getUniqueId());if(s==null||s.widgetIndex==null)return;
        Chunk widget=s.chunks.get(s.widgetIndex);
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.WIDGET_ADD_ITEM,-1),27,guiConfig.title("widget-add-item-menu",ChatColor.DARK_BLUE+"Add Widget Item"));
        put(inv,widgetAddItemButton(widget.widgetColors,"color",11,Material.RED_WOOL,"&cColor","&7Add a colour/style","&cColors Disabled","&7This widget does not allow colors/styles"));
        put(inv,widgetAddItemButton(widget.widgetPlaceholders,"placeholder",13,Material.NAME_TAG,"&bPlaceholder","&7Add a saved placeholder","&cPlaceholders Disabled","&7This widget does not allow placeholders"));
        put(inv,widgetAddItemButton(widget.widgetText,"text",15,Material.OAK_SIGN,"&fText","&7Add text via sign GUI","&cText Disabled","&7This widget does not allow text"));
        put(inv,guiConfig.button("widget-add-item-menu","back",22,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    private GuiConfigManager.Button widgetAddItemButton(boolean enabled, String key, int slot, Material material,
                                                        String name, String lore, String disabledName, String disabledLore) {
        return enabled ? guiConfig.button("widget-add-item-menu",key,slot,material,name,lore)
                : guiConfig.button("widget-add-item-menu",key+"-disabled",slot,Material.BARRIER,disabledName,disabledLore);
    }
    /** Same picker as {@link #openColors}, but adding into the currently-open widget's contents instead of the top-level format — see {@link View#WIDGET_COLORS}. */
    private void openWidgetColors(Player p){
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.WIDGET_COLORS,-1),27,guiConfig.title("colors-menu",ChatColor.DARK_BLUE+"Select Color"));
        for(ColorChoice c:COLOR_CHOICES){
            GuiConfigManager.Button b=guiConfig.button("colors-menu",c.key(),c.fallbackSlot(),c.fallbackMaterial(),c.fallbackName(),"&7Color/style — click to edit");
            inv.setItem(b.slot(),item(b.material(),b.name(),b.loreArray()));
        }
        put(inv,guiConfig.button("colors-menu","back",26,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    /** Same picker as {@link #openPlaceholders}, but adding into the currently-open widget's contents instead of the top-level format — see {@link View#WIDGET_PLACEHOLDERS}. */
    private void openWidgetPlaceholders(Player p){
        Inventory inv=Bukkit.createInventory(new Holder(p.getUniqueId(),View.WIDGET_PLACEHOLDERS,-1),27,guiConfig.title("placeholders-menu",ChatColor.DARK_BLUE+"Select Placeholder"));
        inv.setItem(0,usernamePlaceholderItem(p));
        int back=guiConfig.slot("placeholders-menu","back",26);
        int i=1;for(var x:placeholders.getAll()){if(i>=back)break;inv.setItem(i++,placeholderItem(p,x));}
        put(inv,guiConfig.button("placeholders-menu","back",26,Material.OAK_DOOR,"&eBack"));
        p.openInventory(inv);
    }
    /**
     * Saves whatever's currently in the editor. A line (or per-line
     * {@code {chars N}} override, or a widget's own {@code limit=}) longer
     * than its character limit is no longer rejected here — it's simply
     * let through and saved as-is, warning the editor in chat that it'll
     * show up truncated. The actual truncation happens where it always
     * has, at render time (see {@code NametagManager#computeFullText} for
     * line limits and {@code NametagManager#parseFormat} for widget
     * limits) — the up-front check here could only ever verify against
     * placeholder values known at the moment of saving anyway, and a
     * placeholder like {@code %luckperms_prefix%} can legitimately expand
     * to a different length later, so blocking the save outright never
     * actually guaranteed anything past that first render.
     */
    private void confirm(Player p,Session s) {
        String raw=serialize(s); boolean ownFormat=s.target==Target.PLAYER_EDIT;
        if(raw.isEmpty()){p.sendMessage(ChatColor.RED+"Your nametag format cannot be empty.");return;}
        int characterLimit=ownFormat?NametagFormatPermissions.effectiveLineCharacterLimit(config,p):s.target==Target.PLAYER?characterLimit(s.targetId):-1;
        int[] characterOverrides=TemplateMarkers.lineCharacterOverrides(raw);
        Player contextPlayer=ownFormat?p:(s.target==Target.PLAYER?Bukkit.getPlayer(UUID.fromString(s.targetId)):p);
        if(contextPlayer!=null){
            List<String> plainLines=new ArrayList<>();
            for(Component line:afx.customplayernametags.format.NametagFormatter.splitLines(afx.customplayernametags.format.NametagFormatter.toComponent(manager.parseFormat(contextPlayer,raw))))
                plainLines.add(afx.customplayernametags.format.NametagFormatter.plainText(line));
            for(int i=0;i<plainLines.size();i++){
                int lineCharLimit=i<characterOverrides.length&&characterOverrides[i]>=0?characterOverrides[i]:characterLimit;
                if(lineCharLimit>=0&&plainLines.get(i).length()>lineCharLimit){
                    p.sendMessage(ChatColor.YELLOW+"Line "+(i+1)+" is over its "+lineCharLimit+" character limit once placeholders and colors are resolved — it'll be shown truncated.");
                }
            }
        }
        if(s.target==Target.PLAYER_EDIT) {
            UUID uuid=p.getUniqueId();
            // A player editing their own applied format can only ever touch Widget slots
            // (see lockedForPlayer) — so unless they already have an explicit individual
            // override on file (in which case that override is still saved as a whole, same
            // as before), what they just did is fill in widget(s) inside an inherited
            // global/group format. That gets persisted separately, keyed by widget position,
            // instead of forking their whole effective format into a brand-new override —
            // see NametagManager#saveWidgetFills and PlayerWidgetFillStore.
            if(manager.hasIndividualFormatOverride(uuid)) manager.setFormatOverride(uuid,raw);
            else manager.saveWidgetFills(uuid,TemplateMarkers.extractWidgetContents(raw));
            sessions.remove(uuid);p.closeInventory();messages.send(p,"format-set-self-success");return;
        }
        switch(s.target){case GLOBAL->{if(s.bedrock)config.setBedrockGlobalFormat(raw);else config.setGlobalFormat(raw);manager.refreshAll();}case PLAYER->{manager.setFormatOverride(UUID.fromString(s.targetId),raw);notifyPlayerFormatChanged(p,s.targetId,raw);}case GROUP->{manager.getGroupFormatStore().set(s.targetId,raw,s.bedrock);manager.refreshAll();}default->{}}
        sessions.remove(p.getUniqueId());p.closeInventory();p.sendMessage(ChatColor.GREEN+"Updated nametag format.");
    }
    /**
     * Tells the target player in chat that their individual nametag format
     * was just changed by another player through this editor, per
     * {@code nametag-format-notify-mode} — see
     * {@link afx.customplayernametags.command.NametagCommand#notifyFormatChanged}
     * for the equivalent command-driven path. The GUI editor has no
     * announce/silent argument, so BOTH mode simply defaults to notifying,
     * same as NOTIFY.
     */
    private void notifyPlayerFormatChanged(Player editor, String targetId, String newRawFormat) {
        Player target = Bukkit.getPlayer(UUID.fromString(targetId));
        if (target == null || target.getUniqueId().equals(editor.getUniqueId())) return;
        boolean notify = config.getNotifyMode() != ConfigManager.NotifyMode.SILENT;
        Boolean override = NametagFormatPermissions.notifyOverride(target);
        if (override != null) notify = override;
        if (notify) target.sendMessage(manager.buildFormatChangedNotify(config, editor, target, newRawFormat));
    }
    public void openAdminGui(Player p){
        Inventory i=Bukkit.createInventory(new Holder(p.getUniqueId(),View.ADMIN,-1),27,guiConfig.title("admin-menu",ChatColor.DARK_BLUE+"Nametag Format Admin"));
        put(i,guiConfig.button("admin-menu","global",11,Material.BEACON,"&6Global"));
        put(i,guiConfig.button("admin-menu","player",13,Material.PLAYER_HEAD,"&bPlayer"));
        put(i,guiConfig.button("admin-menu","groups",15,Material.WRITABLE_BOOK,"&dGroups"));
        put(i,guiConfig.button("admin-menu","close",22,Material.BARRIER,"&cClose"));
        p.openInventory(i);
    }
    /** Java-or-Bedrock chooser shown before editing the global format — only reached when {@code enable-separate-bedrock-global-format} is on (see the ADMIN click handling in {@link #handleInventoryClick}). */
    private void openGlobalPlatformChoice(Player p){
        Inventory i=Bukkit.createInventory(new Holder(p.getUniqueId(),View.GLOBAL_PLATFORM_CHOICE,-1),27,guiConfig.title("platform-choice-menu",ChatColor.DARK_BLUE+"Global Format: Platform"));
        put(i,guiConfig.button("platform-choice-menu","java",11,Material.GRASS_BLOCK,"&aJava","&7Edit the normal (Java Edition) global format"));
        put(i,guiConfig.button("platform-choice-menu","bedrock",15,Material.NETHERITE_BOOTS,"&bBedrock","&7Edit the separate Bedrock global format"));
        put(i,guiConfig.button("platform-choice-menu","back",22,Material.OAK_DOOR,"&eBack"));
        p.openInventory(i);
    }
    /** Java-or-Bedrock chooser shown before opening the group list — only reached when {@code enable-separate-bedrock-group-formats} is on (see the ADMIN click handling in {@link #handleInventoryClick}). Mirrors {@link #openGlobalPlatformChoice}; unlike that one, either choice leads to a list ({@link #openGroups}) rather than straight into the chunk editor, since a platform choice for groups is "which list of groups" rather than "which single format". */
    private void openGroupsPlatformChoice(Player p){
        Inventory i=Bukkit.createInventory(new Holder(p.getUniqueId(),View.GROUPS_PLATFORM_CHOICE,-1),27,guiConfig.title("groups-platform-choice-menu",ChatColor.DARK_BLUE+"Groups: Platform"));
        put(i,guiConfig.button("groups-platform-choice-menu","java",11,Material.GRASS_BLOCK,"&aJava","&7Browse Java Edition group formats"));
        put(i,guiConfig.button("groups-platform-choice-menu","bedrock",15,Material.NETHERITE_BOOTS,"&bBedrock","&7Browse Bedrock group formats"));
        put(i,guiConfig.button("groups-platform-choice-menu","back",22,Material.OAK_DOOR,"&eBack"));
        p.openInventory(i);
    }
    private void openPlayers(Player p){
        Inventory i=Bukkit.createInventory(new Holder(p.getUniqueId(),View.PLAYERS,-1),54,guiConfig.title("players-menu",ChatColor.DARK_BLUE+"Select Player"));
        int back=guiConfig.slot("players-menu","back",53);
        int slot=0;
        for(Player q:Bukkit.getOnlinePlayers()){
            if(slot>=back)break;
            i.setItem(slot++,item(Material.PLAYER_HEAD,ChatColor.AQUA+q.getName()));
        }
        put(i,guiConfig.button("players-menu","back",53,Material.OAK_DOOR,"&eBack"));
        p.openInventory(i);
    }
    /**
     * @param bedrock whether to list/edit the Bedrock variant of each
     *                group's format instead of the normal (Java) one —
     *                chosen up front by {@link #openGroupsPlatformChoice}
     *                when {@code enable-separate-bedrock-group-formats} is
     *                on, and fixed for the lifetime of this screen (no
     *                in-menu toggle to switch platform once open — going
     *                back and re-entering "Groups" re-asks instead).
     */
    private void openGroups(Player p, boolean bedrock){
        boolean separateBedrock=config.isSeparateBedrockGroupFormatsEnabled();
        String defaultTitle=separateBedrock?(bedrock?"Select Bedrock Group":"Select Java Group"):"Select Group";
        Inventory i=Bukkit.createInventory(new Holder(p.getUniqueId(),View.GROUPS,bedrock?1:0),27,guiConfig.title("groups-menu",ChatColor.DARK_BLUE+defaultTitle));
        int back=guiConfig.slot("groups-menu","back",26);
        int slot=0;
        for(String g:manager.getGroupFormatStore().getGroupNames(bedrock)){
            if(slot>=back)break;
            i.setItem(slot++,item(Material.WRITABLE_BOOK,ChatColor.LIGHT_PURPLE+g));
        }
        put(i,guiConfig.button("groups-menu","back",26,Material.OAK_DOOR,"&eBack"));
        p.openInventory(i);
    }
    private int characterLimit(String id){Player q=Bukkit.getPlayer(UUID.fromString(id));return q==null?-1:NametagFormatPermissions.effectiveLineCharacterLimit(config,q);}
    /**
     * Renders an already-added chunk for the editor grid. Each kind's item
     * always mirrors whatever material is currently configured in gui.yml
     * for the button that <em>adds</em> that kind of chunk — text pieces
     * use add-item-menu's "text" material, placeholders use its
     * "placeholder" material, newlines use its "newline" material,
     * Widget uses its "widget" material, and a
     * color/style chunk uses colors-menu's material for that specific
     * color/style key — so a chunk in the grid never shows a different
     * item than the button a player actually clicked to add it, even
     * after an admin re-themes gui.yml.
     *
     * @param interactive whether this chunk is actually clickable for the
     *                    viewer — {@code false} for a restricted player
     *                    (see {@link #lockedForPlayer}) viewing a non-Widget
     *                    chunk of their own applied format, in which case
     *                    the usual "click to edit" lore line is dropped
     *                    since it would be misleading. A WIDGET chunk is
     *                    always interactive regardless of this flag — see
     *                    {@link #widgetChunkItem}.
     */
    private ItemStack chunkItem(Player p, Chunk c, boolean interactive){
        return switch(c.kind){
            case TEXT->interactive
                    ?item(guiConfig.material("add-item-menu","text",Material.OAK_SIGN),ChatColor.WHITE+c.value,ChatColor.GRAY+"Text — click to edit")
                    :item(guiConfig.material("add-item-menu","text",Material.OAK_SIGN),ChatColor.WHITE+c.value);
            case PLACEHOLDER->placeholderChunkItem(p,c.value,interactive);
            case COLOR->colorItem(c.value,interactive);
            case NEWLINE->interactive
                    ?item(guiConfig.material("add-item-menu","newline",Material.FEATHER),ChatColor.GREEN+"New line",ChatColor.GRAY+"Newline — click to edit")
                    :item(guiConfig.material("add-item-menu","newline",Material.FEATHER),ChatColor.GREEN+"New line");
            case WIDGET->widgetChunkItem(p,c);
        };
    }
    /**
     * A widget chunk already in the format — an item frame whose lore
     * previews whatever's currently inside it, parsed exactly as
     * {@code p} would see it (same preview convention as
     * {@link #placeholderChunkItem}), or {@code (empty)} if the admin left
     * — or the player hasn't yet filled — its slot. Always shows its
     * "click to edit its contents" lore, since a Widget always opens
     * normally for every viewer regardless of {@link #lockedForPlayer}.
     */
    private ItemStack widgetChunkItem(Player p, Chunk c){
        ItemStack result=new ItemStack(guiConfig.material("add-item-menu","widget",Material.ITEM_FRAME)); ItemMeta meta=result.getItemMeta();
        meta.setDisplayName(ChatColor.LIGHT_PURPLE+"Widget");
        List<Component> lore=new ArrayList<>();
        lore.add(Component.text("Click to edit its contents",NamedTextColor.GRAY));
        if(c.widgetContents==null||c.widgetContents.isEmpty()){
            lore.add(Component.text("(empty)",NamedTextColor.DARK_GRAY));
        } else {
            StringBuilder raw=new StringBuilder(); for(Chunk inner:c.widgetContents)raw.append(inner.value);
            Component parsed=afx.customplayernametags.format.NametagFormatter.toComponent(manager.parseFormat(p,raw.toString()));
            lore.addAll(afx.customplayernametags.format.NametagFormatter.splitLines(parsed));
        }
        meta.lore(lore); result.setItemMeta(meta); return result;
    }
    /**
     * A placeholder chunk already added to the format — like
     * {@link #placeholderItem}, its lore shows the placeholder parsed
     * exactly as {@code p} would currently see it (beneath the usual
     * click-to-edit hint, when {@code interactive}), so a player scanning
     * their format's grid can see up front what a placeholder chunk will
     * actually look like for them, not just its raw {@code %...%} token.
     *
     * <p>The built-in {@code {player}} token stays a {@code PLACEHOLDER}
     * chunk like any other (see {@link #parseToken}) but keeps the same
     * player-head icon it's given in the picker (see
     * {@link #usernamePlaceholderItem}) rather than the generic
     * {@code add-item-menu.placeholder} material every other placeholder
     * chunk uses, so it stays visually identifiable once it's sitting in
     * the format grid.
     */
    private ItemStack placeholderChunkItem(Player p, String value, boolean interactive){
        Material material = value.equals("{player}")
                ? Material.PLAYER_HEAD
                : guiConfig.material("add-item-menu","placeholder",Material.NAME_TAG);
        ItemStack result=new ItemStack(material);
        ItemMeta meta=result.getItemMeta();
        meta.setDisplayName(ChatColor.AQUA+value);
        List<Component> lore=new ArrayList<>();
        if(interactive)lore.add(Component.text("Placeholder — click to edit",NamedTextColor.GRAY));
        Component parsed=afx.customplayernametags.format.NametagFormatter.toComponent(manager.parseFormat(p,value));
        lore.addAll(afx.customplayernametags.format.NametagFormatter.splitLines(parsed));
        meta.lore(lore);
        result.setItemMeta(meta);
        return result;
    }
    /**
     * A color/style chunk's key is always its MiniMessage tag with the
     * angle brackets stripped (e.g. {@code "<dark_red>"} → {@code "dark_red"}),
     * which is exactly the key colors-menu uses for that same entry in
     * gui.yml — so looking the material up there is what keeps this in
     * sync with whatever's actually configured for the "Select Color" page,
     * rather than an independently-hardcoded guess at the item.
     * {@link #materialFor} is only the fallback for a tag with no matching
     * colors-menu entry at all (e.g. one of the legacy-only tags no longer
     * offered as a picker choice, like {@code <underlined>}).
     */
    private ItemStack colorItem(String color, boolean interactive){
        String key=color.length()>=2&&color.startsWith("<")&&color.endsWith(">")?color.substring(1,color.length()-1):color;
        return interactive
                ?item(guiConfig.material("colors-menu",key,materialFor(color)),ChatColor.WHITE+color,ChatColor.GRAY+"Color/style — click to edit")
                :item(guiConfig.material("colors-menu",key,materialFor(color)),ChatColor.WHITE+color);
    }
    private static Material materialFor(String value){String v=value.toLowerCase(Locale.ROOT);if(v.contains("rainbow"))return Material.FIREWORK_STAR;if(v.contains("gradient"))return Material.NAUTILUS_SHELL;if(v.contains("red"))return Material.RED_WOOL;if(v.contains("blue"))return Material.BLUE_WOOL;if(v.contains("green"))return Material.GREEN_WOOL;if(v.contains("yellow")||v.contains("gold"))return Material.YELLOW_WOOL;if(v.contains("purple"))return Material.PURPLE_WOOL;if(v.contains("aqua"))return Material.CYAN_WOOL;if(v.contains("black"))return Material.BLACK_WOOL;if(v.contains("white"))return Material.WHITE_WOOL;if(v.contains("gray"))return Material.GRAY_WOOL;return Material.ORANGE_WOOL;}
    private static ItemStack item(Material m,String name,String... lore){ItemStack s=new ItemStack(m);ItemMeta meta=s.getItemMeta();meta.setDisplayName(name);if(lore.length>0)meta.setLore(Arrays.asList(lore));s.setItemMeta(meta);return s;}
    /** Renders a configured button into {@code inv} at its own configured slot. */
    private static void put(Inventory inv, GuiConfigManager.Button b){ inv.setItem(b.slot(), item(b.material(), b.name(), b.loreArray())); }
    private static List<Chunk> parse(String raw){List<Chunk> out=new ArrayList<>();if(raw==null)return out;Matcher m=TOKEN.matcher(raw);int last=0;while(m.find()){if(m.start()>last)out.add(new Chunk(Kind.TEXT,raw.substring(last,m.start())));out.add(parseToken(m.group()));last=m.end();}if(last<raw.length())out.add(new Chunk(Kind.TEXT,raw.substring(last)));return out;}
    /** Builds the right {@link Chunk} (kind + any nested widget data) for one already-matched {@link #TOKEN} match. */
    private static Chunk parseToken(String x){
        if(x.equals("\\n")||x.equals("\n"))return new Chunk(Kind.NEWLINE,"\\n");
        if(x.startsWith(TemplateMarkers.WIDGET_OPEN_PREFIX)){
            Chunk widget=new Chunk(Kind.WIDGET,x);
            TemplateMarkers.Widget parsed=TemplateMarkers.parseWidget(x);
            // Carried straight through from the tag rather than regenerated — this is what keeps
            // a player's already-stored fill (keyed by this same id, see PlayerWidgetFillStore)
            // attached to this widget across edit sessions. Every widget reaching here should
            // already have an id (ConfigManager/GroupFormatStore/PlayerFormatStore all run
            // TemplateMarkers#ensureWidgetIds on load), but mint one on the spot as a fallback
            // rather than ever leaving a widget id-less in the editor.
            widget.widgetId=parsed.id()==null||parsed.id().isEmpty()?TemplateMarkers.generateWidgetId():parsed.id();
            widget.widgetColors=parsed.colors();
            widget.widgetPlaceholders=parsed.placeholders();
            widget.widgetText=parsed.text();
            widget.widgetCharacterLimit=parsed.characterLimit();
            // Widget contents are only ever TEXT/COLOR/PLACEHOLDER chunks (never
            // newlines or another widget), so the outer tokenizer can safely
            // re-run over the inner raw string to reconstruct them.
            widget.widgetContents=parse(parsed.inner());
            return widget;
        }
        if(x.equals("{player}"))return new Chunk(Kind.PLACEHOLDER,x);
        if(x.startsWith("%"))return new Chunk(Kind.PLACEHOLDER,x);
        if(x.startsWith("&")||x.startsWith("<"))return new Chunk(Kind.COLOR,x);
        return new Chunk(Kind.TEXT,x);
    }
    private static String serialize(Session s){StringBuilder b=new StringBuilder();for(Chunk c:s.chunks)b.append(c.kind==Kind.NEWLINE?"\\n":c.value);return b.toString();}
    /**
     * Rebuilds a widget chunk's {@code value} (its {@link TemplateMarkers}
     * tag text) from its current flags and {@code widgetContents} —
     * must be called after any edit to either, or {@link #serialize} would
     * keep emitting the widget's stale pre-edit contents.
     */
    private static void resyncWidget(Chunk widget){
        StringBuilder inner=new StringBuilder();
        for(Chunk c:widget.widgetContents)inner.append(c.value);
        widget.value=TemplateMarkers.encodeWidget(widget.widgetId,widget.widgetColors,widget.widgetPlaceholders,widget.widgetText,widget.widgetCharacterLimit,inner.toString());
    }
    /**
     * One selectable entry on the "Select Color" page: {@code key} is its
     * gui.yml config key (e.g. {@code "dark_blue"}), {@code tag} is the
     * actual MiniMessage tag added to the format when clicked (e.g.
     * {@code "<dark_blue>"}) and never changes regardless of gui.yml, and
     * {@code fallbackSlot}/{@code fallbackMaterial}/{@code fallbackName} are
     * what's used if gui.yml doesn't override this entry.
     */
    private record ColorChoice(String key, String tag, int fallbackSlot, Material fallbackMaterial, String fallbackName) {}
    private static final List<ColorChoice> COLOR_CHOICES=createColorChoices();
    private static List<ColorChoice> createColorChoices(){
        // Deliberately omits <underlined>, <strikethrough>, and <reset> —
        // no longer offered as selectable colors/styles in the "Select
        // Color" editor menu. A format that already contains one of those
        // tags (set directly in config.yml, a preset, etc.) still renders
        // and parses exactly as before; only the picker no longer offers them.
        String[] tags={"<black>","<dark_blue>","<dark_green>","<dark_aqua>","<dark_red>","<dark_purple>","<gold>","<gray>","<dark_gray>","<blue>","<green>","<aqua>","<red>","<light_purple>","<yellow>","<white>","<bold>","<italic>","<obfuscated>","<rainbow>"};
        List<ColorChoice> out=new ArrayList<>();
        for(int i=0;i<tags.length;i++){
            String tag=tags[i]; String key=tag.substring(1,tag.length()-1);
            out.add(new ColorChoice(key,tag,i,materialFor(tag),ChatColor.WHITE+friendlyLabel(key)));
        }
        return out;
    }
    /**
     * Turns a colors-menu key like {@code "dark_red"} into a friendly
     * display label like {@code "Dark Red"} — purely cosmetic for the
     * "Select Color" picker. What actually gets added to the format when
     * clicked is always {@link ColorChoice#tag()} (e.g. {@code <dark_red>}),
     * so once it's in the editor grid it's shown as its raw tag again, same
     * as every other chunk.
     */
    private static String friendlyLabel(String key){
        StringBuilder out=new StringBuilder();
        for(String word:key.split("_")){
            if(word.isEmpty())continue;
            if(out.length()>0)out.append(' ');
            out.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
        }
        return out.toString();
    }
}